ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.12
  hooks:
  - id: uv-lock

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: [--skip, '*.dat', --ignore-words-list, accreting]

- repo: https://github.com/neutrinoceros/inifix.git
  rev: v6.1.1
  hooks:
  - id: inifix-format
    files: \.ini$
    args: [--sections=require]
  - id: inifix-validate
    name: Validate .par files (no formatting)
    files: \.par$
    args: [--sections=forbid]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.9
  hooks:
  - id: ruff-format
  - id: ruff-check
    args: [--fix, --show-fixes]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
